sudo: required

services:
  - docker

before_install:
  - docker build -t rafaelnasc1mento/backend-app -f Dockerfile.dev .

script:
  - docker run rafaelnasc1mento/backend-app mvn test
  
deploy:
  # travis comes pre-configured with a bunch of cloud providers
  provider: elasticbeanstalk  
  region: "sa-east-1"
  app: "backend-app"
  environment: "BackendApp-env"
  bucket-name: elasticbeanstalk-sa-east-1-423672971386
  bucket-path: "backend-app"
  on:
    branch: master
  env:
    - ACCESS_KEY_ID: "$AWS_ACCESS_KEY"
    - SECRET_ACCESS_KEY: "$AWS_SECRET_KEY"